name: LocalStack Cloud Pods Test

on:
  schedule:
    # “At 00:00 on Sunday.”
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cloud-pods:
    name: Cloud Pods Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start LocalStack
        env:
          DNS_ADDRESS: 0
        run: |
          pip install localstack awscli-local[ver1]
          docker pull localstack/localstack:latest
          # Start LocalStack in the background
          LS_LOG=trace localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 15
          echo "Startup complete"

      - name: Inject Cloud Pod
        run: |
          localstack pod load file://$(pwd)/cloud-pod/loan-broker-application
          sleep 15
          awslocal lambda list-functions 
          awslocal sqs list-queues 
          awslocal dynamodb list-tables
          awslocal stepfunctions list-state-machines

      - name: Send a Slack notification
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow run>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz
